services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alugueis_user -d alugueis"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    user: "1000:1000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "./wait-for-it.sh db && PYTHONPATH=/app alembic upgrade heads && PYTHONPATH=/app uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: