version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./alugueis.db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
    user: appuser:appuser  # Restaurado para segurança
    restart: unless-stopped
    command: sh -c "python -c 'from app.core.database import engine, Base; Base.metadata.create_all(bind=engine); print(\"Tabelas criadas!\")' && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"