"""Initial migration

Revision ID: 89c3a04cb4d4
Revises:
Create Date: 2024-01-01 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c3a04cb4d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('endereco', sa.Text(), nullable=False),
    sa.Column('alugado', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alias_proprietarios',
    sa.Column('id_alias', sa.Integer(), nullable=False),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_alias'], ['alias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proprietario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_alias', 'id_proprietario')
    )
    op.create_table('participacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_imovel', sa.Integer(), nullable=False),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('participacao', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_imovel'], ['imoveis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proprietario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participacoes_data', 'participacoes', ['data_cadastro'], unique=False)
    op.create_table('permissoes_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('visualizar', sa.Boolean(), nullable=True),
    sa.Column('editar', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_perm_fin_usuario_prop', 'permissoes_financeiras', ['id_usuario', 'id_proprietario'], unique=True)
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_alias', sa.Integer(), nullable=False),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_alias'], ['alias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proprietario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transferencias_periodo', 'transferencias', ['data_inicio', 'data_fim'], unique=False)
    op.create_table('alugueis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_imovel', sa.Integer(), nullable=False),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('aluguel_liquido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('taxa_administracao_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('darf', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_imovel'], ['imoveis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_proprietario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alugueis_data', 'alugueis', ['data_cadastro'], unique=False)
    op.create_index('idx_alugueis_imovel_prop', 'alugueis', ['id_imovel', 'id_proprietario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alugueis_imovel_prop', table_name='alugueis')
    op.drop_index('idx_alugueis_data', table_name='alugueis')
    op.drop_table('alugueis')
    op.drop_index('idx_transferencias_periodo', table_name='transferencias')
    op.drop_table('transferencias')
    op.drop_index('idx_perm_fin_usuario_prop', table_name='permissoes_financeiras')
    op.drop_table('permissoes_financeiras')
    op.drop_index('idx_participacoes_data', table_name='participacoes')
    op.drop_table('participacoes')
    op.drop_table('alias_proprietarios')
    op.drop_table('usuarios')
    op.drop_table('imoveis')
    op.drop_table('alias')
    # ### end Alembic commands ###